### PR TITLE
AdSlot Fix & Typography Fixes

### LINKED ISSUE #251: can not create ad slot with passback
When creating Ad Slot with passback, market returns error
image

### LINKED ISSUE #252: UX/UI: Waiting for Metamask action: better visualisation of text
Now it looks like this: 
Screenshot 2019-12-04 at 14 43 17

I suggest we make it look like this: 
Screenshot 2019-12-04 at 14 43 17-2

The idea of a reminder is very good, but it is not easy to spot right now - text layout is bad, the position of the message is not where your look is (The button "Save Campaign"), etc.

### LINKED ISSUE #253: UX/UI: Better Identity Balance Info Visualisation
Font size should be at least 1.5x the rest. Numbers should be in bold.

identitybalance

### PR DESCRIPTION
**Pull request by rori4**
- fixes UX/UI: Better Identity Balance Info Visualisation (closes #253)
- fixes UX/UI: Waiting for Metamask action: better visualisation of text (closes #252)
- fixes can not create ad slot with passback (closes #251)

### CODE REVIEW

File: src/components/common/dialog/content.js [hunk 1]
```diff
@@ -60,10 +60,17 @@ const contentStickyTop = ({ classes, children, className }) => (
 	<div className={classnames(classes.contentStickyTop)}>{children}</div>
 )
 
-const topLoading = ({ classes, msg, className }) => (
+const topLoading = ({ classes, msg, subMsg, className }) => (
 	<div className={classnames(classes.contentTopLoading)}>
 		<CircularProgress className={classes.contentTopLoadingCircular} size={50} />
-		<div> {msg} </div>
+		<div>
```
Comment (IvoPaunov) [inline src/components/common/dialog/content.js]: Can you make it with Typography.
