### PR TITLE
UI Minor Fixes Patch 1

### LINKED ISSUE #88: UX: explain what targeting scores are
initial users seem to be finding the 0-100 slider confusing

we have to either explain it, or make it a select: priority/importance/weight: "Low", "Medium", "High

### LINKED ISSUE #156: Before data is loaded dashboard amount is set to undefined
**Description**
Before dashboard data is loaded it says `undefined` It should be initialized with 0. To make page more responsive loading indicator could be added.
**Screenshots**
Undefined wasn't catch on screenshots, but this is the place where it happend.
image

### LINKED ISSUE #159: Add space between Backup Wallet and Copy buttons
**Description**
As you can see on the screenshots there is no space between buttons.
**Screenshots**
image

### LINKED ISSUE #160: Account section - addresses
**Description**
1.  First leter in `grant` should be capitalized 
2. Identity address is above label, for grant address it is below the label to make it consistent they should be in the same order.
**Screenshots**
image

### PR DESCRIPTION
**Pull request by rori4**
- fix Add space between Backup Wallet and Copy buttons (closes #159 )
- fix Before data is loaded dashboard amount is set to undefined (closes #156 )
- fix Account section - addresses (closes #160)
- fix UX: explain what targeting scores are (closes #88)
- fix targeting scores css

### CODE REVIEW

File: src/components/dashboard/containers/DashboardStats/DashboardStats.js [hunk 1]
```diff
@@ -268,9 +268,14 @@ export class DashboardStats extends Component {
 					linkCard
 					onClick={this.goToAccount}
 					subtitle={t('IDENTITY_DAI_BALANCE_AVAILABLE_INFO', {
-						args: [identityBalanceDai, outstandingBalanceDai],
+						args: [identityBalanceDai || 0, outstandingBalanceDai || 0],
```
Comment (IvoPaunov) [inline src/components/dashboard/containers/DashboardStats/DashboardStats.js]: Can you check if the balances are undefined or null and show "N/A" or "Loading...", and `0` if they are '0'

Comment (IvoPaunov) [reply src/components/dashboard/containers/DashboardStats/DashboardStats.js]: OK it has loading ..., that's OK. Just make sure if all balances are 0, to show 0
